<?php

namespace Tests;

use PHPUnit\Framework\TestCase;
use swkberlin\Kata;

require __DIR__ . '/../vendor/autoload.php';

class KataTest extends TestCase
{
    private $kata;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->kata = new Kata();

    }

    public function testRomanNumber() {
        $expect = 'IIII';
        $actual = $this->kata->charRepeat('I', 4);
        $this->assertEquals($expect, $actual);
    }

    public function testSix() {
        $expect = 'VI';

        $actual = $this->kata->charRepeat(6 );

        $this->assertEquals($expect, $actual);
    }

    public function testGetSpecialRoman() {
        $expect = 'X';
        $actual = $this->kata->getSpecialRoman(10);

        $this->assertEquals( $expect, $actual );
    }

    public function testToRoman() {
        $expect = 'VI';
        $actual = $this->kata->toRoman(6);

        $this->assertEquals($expect, $actual);
    }
}
